--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.688.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12.09.2021 09:43:33
-- Server version: 5.7.35
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE bills_local;

--
-- Drop table `accounts`
--
DROP TABLE IF EXISTS accounts;

--
-- Drop table `agreements`
--
DROP TABLE IF EXISTS agreements;

--
-- Drop table `bills`
--
DROP TABLE IF EXISTS bills;

--
-- Drop table `business_items`
--
DROP TABLE IF EXISTS business_items;

--
-- Drop table `calendar`
--
DROP TABLE IF EXISTS calendar;

--
-- Drop table `messages`
--
DROP TABLE IF EXISTS messages;

--
-- Drop table `message_types`
--
DROP TABLE IF EXISTS message_types;

--
-- Drop table `objects`
--
DROP TABLE IF EXISTS objects;

--
-- Drop table `payers`
--
DROP TABLE IF EXISTS payers;

--
-- Drop table `payments`
--
DROP TABLE IF EXISTS payments;

--
-- Drop table `payment_statuses`
--
DROP TABLE IF EXISTS payment_statuses;

--
-- Drop table `payment_transactions`
--
DROP TABLE IF EXISTS payment_transactions;

--
-- Drop table `payment_types`
--
DROP TABLE IF EXISTS payment_types;

--
-- Drop table `period_calendar`
--
DROP TABLE IF EXISTS period_calendar;

--
-- Drop table `settings`
--
DROP TABLE IF EXISTS settings;

--
-- Drop table `transactions`
--
DROP TABLE IF EXISTS transactions;

--
-- Drop table `addresses`
--
DROP TABLE IF EXISTS addresses;

--
-- Drop table `address_types`
--
DROP TABLE IF EXISTS address_types;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Drop table `user_roles`
--
DROP TABLE IF EXISTS user_roles;

--
-- Set default database
--
USE bills_local;

--
-- Create table `user_roles`
--
CREATE TABLE user_roles (
  role_id VARCHAR(50) NOT NULL,
  orderby INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (role_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `users`
--
CREATE TABLE users (
  user_id INT(11) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  user VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role_id VARCHAR(255) NOT NULL,
  is_active SMALLINT(6) NOT NULL DEFAULT 1,
  hiring_date DATE DEFAULT NULL,
  closure_date DATE DEFAULT NULL,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE users 
  ADD CONSTRAINT FK_users_role_id FOREIGN KEY (role_id)
    REFERENCES user_roles(role_id);

--
-- Create table `address_types`
--
CREATE TABLE address_types (
  address_type VARCHAR(100) NOT NULL,
  PRIMARY KEY (address_type)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `addresses`
--
CREATE TABLE addresses (
  address_id BIGINT(20) NOT NULL,
  address_type_id VARCHAR(100) DEFAULT NULL,
  location VARCHAR(200) NOT NULL,
  PRIMARY KEY (address_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE addresses 
  ADD CONSTRAINT FK_address_type_ FOREIGN KEY (address_type_id)
    REFERENCES address_types(address_type);

--
-- Create table `transactions`
--
CREATE TABLE transactions (
  transaction_id BIGINT(20) NOT NULL,
  payment_id INT(11) DEFAULT NULL,
  account_id INT(11) DEFAULT NULL,
  amount DECIMAL(14, 4) DEFAULT NULL,
  created_date DATETIME DEFAULT NULL,
  created_by INT(11) DEFAULT NULL,
  updated_date DATETIME DEFAULT NULL,
  updated_by INT(11) DEFAULT NULL,
  is_cancelled SMALLINT(6) NOT NULL DEFAULT 0,
  PRIMARY KEY (transaction_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `settings`
--
CREATE TABLE settings (
  setting_id BIGINT(20) NOT NULL,
  s_key VARCHAR(255) DEFAULT NULL,
  value VARCHAR(255) DEFAULT NULL,
  required SMALLINT(6) NOT NULL,
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  created_by INT(11) DEFAULT NULL,
  updated_date DATETIME DEFAULT NULL,
  updated_by INT(11) DEFAULT NULL,
  PRIMARY KEY (setting_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `period_calendar`
--
CREATE TABLE period_calendar (
  period_id BIGINT(20) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  PRIMARY KEY (period_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1365,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `payment_types`
--
CREATE TABLE payment_types (
  payment_type_id VARCHAR(255) NOT NULL,
  PRIMARY KEY (payment_type_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `payment_transactions`
--
CREATE TABLE payment_transactions (
  payment_id INT(11) NOT NULL,
  transaction_id INT(11) NOT NULL,
  created_date DATETIME NOT NULL,
  created_by INT(11) NOT NULL,
  updated_date DATETIME DEFAULT NULL,
  updated_by INT(11) DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `payment_statuses`
--
CREATE TABLE payment_statuses (
  status CHAR(1) NOT NULL,
  status_description VARCHAR(255) NOT NULL,
  PRIMARY KEY (status)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `payments`
--
CREATE TABLE payments (
  payment_id BIGINT(20) NOT NULL,
  payer_id INT(11) NOT NULL,
  amount FLOAT(14, 4) NOT NULL,
  payment_date DATE NOT NULL,
  bank_statements_date DATE DEFAULT NULL,
  bank_statement_description TEXT DEFAULT NULL,
  payment_status CHAR(1) NOT NULL,
  payment_type_id VARCHAR(255) NOT NULL,
  bank_statements_number INT(11) DEFAULT NULL,
  is_cancelled SMALLINT(6) NOT NULL DEFAULT 0,
  created_by INT(11) DEFAULT NULL,
  created_date DATETIME DEFAULT NULL,
  updated_by INT(11) DEFAULT NULL,
  updated_date DATETIME DEFAULT NULL,
  PRIMARY KEY (payment_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `payers`
--
CREATE TABLE payers (
  payer_id BIGINT(20) NOT NULL,
  full_name VARCHAR(255) DEFAULT NULL,
  telephon_number VARCHAR(255) DEFAULT NULL,
  old_telephon_number VARCHAR(255) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  bank_filter_id INT(11) DEFAULT NULL,
  agreement_id INT(11) DEFAULT NULL,
  billing_address VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (payer_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `objects`
--
CREATE TABLE objects (
  object_id BIGINT(20) NOT NULL,
  house_address VARCHAR(255) DEFAULT NULL,
  location VARCHAR(255) DEFAULT NULL,
  payer_id INT(11) NOT NULL,
  apartment_number INT(11) DEFAULT NULL,
  apartment_code VARCHAR(50) DEFAULT NULL,
  front_door_number INT(11) DEFAULT NULL,
  front_door_code VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (object_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `message_types`
--
CREATE TABLE message_types (
  message_type VARCHAR(50) NOT NULL,
  PRIMARY KEY (message_type)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `messages`
--
CREATE TABLE messages (
  message_id INT(11) NOT NULL,
  payer_id INT(11) DEFAULT NULL,
  message_type VARCHAR(50) DEFAULT NULL,
  message_text TEXT DEFAULT NULL,
  send_date DATETIME DEFAULT NULL,
  updated DATETIME DEFAULT NULL,
  updated_by VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (message_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `calendar`
--
CREATE TABLE calendar (
  calendar_id INT(11) NOT NULL,
  c_date DATETIME NOT NULL,
  c_day_of_month SMALLINT(6) NOT NULL,
  c_is_work_day SMALLINT(6) NOT NULL,
  c_month SMALLINT(6) NOT NULL,
  c_year SMALLINT(6) NOT NULL,
  c_quater SMALLINT(6) NOT NULL,
  c_day_of_week SMALLINT(6) NOT NULL,
  c_reason_day_off VARCHAR(100) DEFAULT NULL,
  c_week_of_year SMALLINT(6) DEFAULT NULL,
  c_day_of_year SMALLINT(6) DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `calendar_dates` on table `calendar`
--
ALTER TABLE calendar 
  ADD UNIQUE INDEX calendar_dates(c_date);

--
-- Create table `business_items`
--
CREATE TABLE business_items (
  business_id VARCHAR(50) NOT NULL,
  PRIMARY KEY (business_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1489,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `bills`
--
CREATE TABLE bills (
  bill_id INT(11) NOT NULL,
  payer_id INT(11) DEFAULT NULL,
  period_id INT(11) DEFAULT NULL,
  bill_amount DECIMAL(15, 4) DEFAULT NULL,
  credit_account_id INT(11) DEFAULT NULL,
  debet_account_id INT(11) DEFAULT NULL,
  payment_date DATETIME DEFAULT NULL,
  payment_status CHAR(1) DEFAULT NULL,
  PRIMARY KEY (bill_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `agreements`
--
CREATE TABLE agreements (
  agrement_id BIGINT(20) NOT NULL,
  agreement_header VARCHAR(255) DEFAULT NULL,
  payer_id INT(11) DEFAULT NULL,
  can_be_published SMALLINT(6) DEFAULT NULL,
  PRIMARY KEY (agrement_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `accounts`
--
CREATE TABLE accounts (
  account_id INT(11) NOT NULL,
  payer_id INT(11) NOT NULL,
  account_amount DECIMAL(15, 4) NOT NULL,
  PRIMARY KEY (account_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

-- 
-- Dumping data for table user_roles
--
INSERT INTO user_roles VALUES
('Администратор', 3),
('Бухгалтер', 5),
('Главный бухгалтер', 4),
('Директор', 1),
('Персонал', 6),
('Руководитель', 2);

-- 
-- Dumping data for table address_types
--
INSERT INTO address_types VALUES
('Адрес объекта для оплаты'),
('Адрес плательщика для переписки'),
('Номер плательщика Whatsapp'),
('Номер плательщика в Telegram'),
('Номер плательщика в Viber'),
('Номер телефона плательщика'),
('Физический адрес регистрации плательщика'),
('Электронная почта плательщика'),
('Юридический адрес получателя (ОСББ)');

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, 'Админов Иван', 'admin', 'admin', 'Администратор', 1, NULL, NULL),
(2, 'Башлялкин Сергей', 'boss', 'boss', 'Директор', 1, NULL, NULL),
(6, 'Расчётина Татьяна Игоревна', 'glavbuch', 'glavbuch', 'Главный бухгалтер', 1, NULL, NULL),
(8, 'Мендельсон Абрам Моисеевич', 'znaet', 'znaert', 'Руководитель', 1, NULL, NULL),
(10, 'Скворцова Наталья', 'buch1', 'buch1', 'Бухгалтер', 1, '2021-08-31', NULL),
(14, 'Марков Сергей Валерьевич', 'mark1', 'ssrraa22', 'Главный бухгалтер', 1, '2021-08-28', '2021-08-28'),
(15, 'Ветренный Игорь', 'veter', '111', 'Персонал', 1, '2021-08-29', '2021-08-28'),
(24, 'Малявкин Владимир', 'adm1', 'aaaa', 'Администратор', 1, '2021-08-29', '2021-08-28'),
(25, 'Серенко Сергей', 'adm2', 'adm1', 'Администратор', 1, '2021-08-29', '2021-08-28');

-- 
-- Dumping data for table transactions
--
-- Table bills_local.transactions does not contain any data (it is empty)

-- 
-- Dumping data for table settings
--
INSERT INTO settings VALUES
(1, 'theme', 'dark', 1, NULL, NULL, '2021-09-01 18:14:20', 0),
(2, 'round_money', '1.00', 1, '2021-08-31 19:41:56', NULL, '2021-09-01 18:14:20', 0);

-- 
-- Dumping data for table period_calendar
--
INSERT INTO period_calendar VALUES
(100, '2021-01-01', '2021-01-31'),
(101, '2021-02-01', '2021-02-28'),
(102, '2021-03-01', '2021-03-31'),
(103, '2021-04-01', '2021-04-30'),
(104, '2021-05-01', '2021-05-31'),
(105, '2021-06-01', '2021-06-30'),
(106, '2021-07-01', '2021-07-30'),
(107, '2021-08-01', '2021-08-31'),
(108, '2021-09-01', '2021-09-30'),
(109, '2021-10-01', '2021-10-31'),
(110, '2021-11-01', '2021-11-30'),
(111, '2021-12-01', '2021-12-31');

-- 
-- Dumping data for table payment_types
--
INSERT INTO payment_types VALUES
('Каждую неделю'),
('Каждый год'),
('Каждый квартал'),
('Каждый месяц');

-- 
-- Dumping data for table payment_transactions
--
-- Table bills_local.payment_transactions does not contain any data (it is empty)

-- 
-- Dumping data for table payment_statuses
--
-- Table bills_local.payment_statuses does not contain any data (it is empty)

-- 
-- Dumping data for table payments
--
-- Table bills_local.payments does not contain any data (it is empty)

-- 
-- Dumping data for table payers
--
-- Table bills_local.payers does not contain any data (it is empty)

-- 
-- Dumping data for table objects
--
-- Table bills_local.objects does not contain any data (it is empty)

-- 
-- Dumping data for table message_types
--
INSERT INTO message_types VALUES
('Почтовое с уведомлением'),
('Почтовое сообщение'),
('Сообщение в Telegram'),
('Сообщение в Viber'),
('Сообщение по email'),
('Требование об оплате'),
('Тяжелое требование при задолженности');

-- 
-- Dumping data for table messages
--
-- Table bills_local.messages does not contain any data (it is empty)

-- 
-- Dumping data for table calendar
--
-- Table bills_local.calendar does not contain any data (it is empty)

-- 
-- Dumping data for table business_items
--
INSERT INTO business_items VALUES
('Взносы на капитальный ремонт'),
('Вывоз мусора'),
('Оплата интернет-услуг'),
('Оплата телефонных услуг'),
('Отопление'),
('Поставка газа'),
('Поставка горячей воды'),
('Поставка холодной воды'),
('Поставка электричества'),
('Расходы на ведение ОСББ'),
('Уборка территории');

-- 
-- Dumping data for table bills
--
-- Table bills_local.bills does not contain any data (it is empty)

-- 
-- Dumping data for table agreements
--
-- Table bills_local.agreements does not contain any data (it is empty)

-- 
-- Dumping data for table addresses
--
-- Table bills_local.addresses does not contain any data (it is empty)

-- 
-- Dumping data for table accounts
--
-- Table bills_local.accounts does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;