--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.665.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 16.08.2021 00:13:59
-- Server version: 10.4.20
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE utilbills;

--
-- Drop table `accounts`
--
DROP TABLE IF EXISTS accounts;

--
-- Drop table `agreements`
--
DROP TABLE IF EXISTS agreements;

--
-- Drop table `bills`
--
DROP TABLE IF EXISTS bills;

--
-- Drop table `payers`
--
DROP TABLE IF EXISTS payers;

--
-- Drop table `payment_statuses`
--
DROP TABLE IF EXISTS payment_statuses;

--
-- Drop table `period_calendar`
--
DROP TABLE IF EXISTS period_calendar;

--
-- Set default database
--
USE utilbills;

--
-- Create table `period_calendar`
--
CREATE TABLE period_calendar (
  period_id int(11) UNSIGNED NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  PRIMARY KEY (period_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1365,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `payment_statuses`
--
CREATE TABLE payment_statuses (
  status char(1) NOT NULL,
  status_description varchar(255) NOT NULL,
  PRIMARY KEY (status)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `payers`
--
CREATE TABLE payers (
  payer_id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  full_name varchar(255) DEFAULT NULL,
  telephon_number varchar(255) DEFAULT NULL,
  old_telephon_number varchar(255) DEFAULT NULL,
  email varchar(50) DEFAULT NULL,
  bank_filter_id int(11) DEFAULT NULL,
  agreement_id int(11) DEFAULT NULL,
  billing_address varchar(255) DEFAULT NULL,
  PRIMARY KEY (payer_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `bills`
--
CREATE TABLE bills (
  bill_id int(11) NOT NULL AUTO_INCREMENT,
  payer_id int(11) DEFAULT NULL,
  period_id int(11) DEFAULT NULL,
  bill_amount decimal(15, 4) DEFAULT NULL,
  credit_account_id int(11) DEFAULT NULL,
  debet_account_id int(11) DEFAULT NULL,
  payment_date datetime DEFAULT NULL,
  payment_status char(1) DEFAULT NULL,
  PRIMARY KEY (bill_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `agreements`
--
CREATE TABLE agreements (
  agrement_id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  agreement_header varchar(255) DEFAULT NULL,
  payer_id int(11) DEFAULT NULL,
  can_be_published tinyint(1) DEFAULT NULL,
  PRIMARY KEY (agrement_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `accounts`
--
CREATE TABLE accounts (
  account_id int(11) NOT NULL AUTO_INCREMENT,
  payer_id int(11) NOT NULL,
  account_amount decimal(15, 4) NOT NULL,
  PRIMARY KEY (account_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

-- 
-- Dumping data for table period_calendar
--
INSERT INTO period_calendar VALUES
(100, '2021-01-01', '2021-01-31'),
(101, '2021-02-01', '2021-02-28'),
(102, '2021-03-01', '2021-03-31'),
(103, '2021-04-01', '2021-04-30'),
(104, '2021-05-01', '2021-05-31'),
(105, '2021-06-01', '2021-06-30'),
(106, '2021-07-01', '2021-07-30'),
(107, '2021-08-01', '2021-08-31'),
(108, '2021-09-01', '2021-09-30'),
(109, '2021-10-01', '2021-10-31'),
(110, '2021-11-01', '2021-11-30'),
(111, '2021-12-01', '2021-12-31');

-- 
-- Dumping data for table payment_statuses
--
-- Table utilbills.payment_statuses does not contain any data (it is empty)

-- 
-- Dumping data for table payers
--
-- Table utilbills.payers does not contain any data (it is empty)

-- 
-- Dumping data for table bills
--
-- Table utilbills.bills does not contain any data (it is empty)

-- 
-- Dumping data for table agreements
--
-- Table utilbills.agreements does not contain any data (it is empty)

-- 
-- Dumping data for table accounts
--
-- Table utilbills.accounts does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;