--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.665.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 18.08.2021 07:31:11
-- Server version: 10.4.20
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE utilbills;

--
-- Drop table `accounts`
--
DROP TABLE IF EXISTS accounts;

--
-- Drop table `agreements`
--
DROP TABLE IF EXISTS agreements;

--
-- Drop table `bills`
--
DROP TABLE IF EXISTS bills;

--
-- Drop table `business_items`
--
DROP TABLE IF EXISTS business_items;

--
-- Drop table `calendar`
--
DROP TABLE IF EXISTS calendar;

--
-- Drop table `messages`
--
DROP TABLE IF EXISTS messages;

--
-- Drop table `message_types`
--
DROP TABLE IF EXISTS message_types;

--
-- Drop table `objects`
--
DROP TABLE IF EXISTS objects;

--
-- Drop table `payers`
--
DROP TABLE IF EXISTS payers;

--
-- Drop table `payments`
--
DROP TABLE IF EXISTS payments;

--
-- Drop table `payment_statuses`
--
DROP TABLE IF EXISTS payment_statuses;

--
-- Drop table `payment_transactions`
--
DROP TABLE IF EXISTS payment_transactions;

--
-- Drop table `payment_types`
--
DROP TABLE IF EXISTS payment_types;

--
-- Drop table `period_calendar`
--
DROP TABLE IF EXISTS period_calendar;

--
-- Drop table `settings`
--
DROP TABLE IF EXISTS settings;

--
-- Drop table `transactions`
--
DROP TABLE IF EXISTS transactions;

--
-- Drop table `addresses`
--
DROP TABLE IF EXISTS addresses;

--
-- Drop table `address_types`
--
DROP TABLE IF EXISTS address_types;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Drop table `user_roles`
--
DROP TABLE IF EXISTS user_roles;

--
-- Set default database
--
USE utilbills;

--
-- Create table `user_roles`
--
CREATE TABLE user_roles (
  role_id varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (role_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `users`
--
CREATE TABLE users (
  user_id int(11) NOT NULL,
  full_name varchar(255) NOT NULL,
  user varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  role_id varchar(255) NOT NULL,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE users
ADD CONSTRAINT FK_users_role_id FOREIGN KEY (role_id)
REFERENCES user_roles (role_id);

--
-- Create table `address_types`
--
CREATE TABLE address_types (
  address_type varchar(100) NOT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `address_type_unique` on table `address_types`
--
ALTER TABLE address_types
ADD UNIQUE INDEX address_type_unique (address_type);

--
-- Create table `addresses`
--
CREATE TABLE addresses (
  address_id int(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  address_type_id varchar(100) DEFAULT NULL,
  location varchar(200) NOT NULL,
  PRIMARY KEY (address_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE addresses
ADD CONSTRAINT FK_address_type_ FOREIGN KEY (address_type_id)
REFERENCES address_types (address_type);

--
-- Create table `transactions`
--
CREATE TABLE transactions (
  transaction_id bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  payment_id int(11) DEFAULT NULL,
  account_id int(11) DEFAULT NULL,
  amount decimal(14, 4) DEFAULT NULL,
  created_date datetime DEFAULT NULL,
  created_by int(11) DEFAULT NULL,
  updated_date datetime DEFAULT NULL,
  updated_by int(11) DEFAULT NULL,
  is_cancelled tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (transaction_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `settings`
--
CREATE TABLE settings (
  setting_id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `key` varchar(255) DEFAULT NULL,
  value varchar(255) DEFAULT NULL,
  required tinyint(1) NOT NULL,
  created_date datetime DEFAULT NULL,
  created_by int(11) DEFAULT NULL,
  updated_date datetime DEFAULT NULL,
  update_by int(11) DEFAULT NULL,
  PRIMARY KEY (setting_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
COMMENT = 'Таблица для хранения специальных настроек';

--
-- Create table `period_calendar`
--
CREATE TABLE period_calendar (
  period_id int(11) UNSIGNED NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  PRIMARY KEY (period_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1365,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `payment_types`
--
CREATE TABLE payment_types (
  payment_type_id varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (payment_type_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `payment_transactions`
--
CREATE TABLE payment_transactions (
  payment_id int(11) NOT NULL,
  transaction_id int(11) NOT NULL,
  created_date datetime NOT NULL,
  created_by int(11) NOT NULL,
  updated_date datetime DEFAULT NULL,
  updated_by int(11) DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `payment_statuses`
--
CREATE TABLE payment_statuses (
  status char(1) NOT NULL,
  status_description varchar(255) NOT NULL,
  PRIMARY KEY (status)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `payments`
--
CREATE TABLE payments (
  payment_id bigint(20) NOT NULL AUTO_INCREMENT,
  payer_id int(11) NOT NULL,
  amount float(14, 4) NOT NULL,
  payment_date date NOT NULL,
  bank_statements_date date DEFAULT NULL,
  bank_statement_description varchar(500) DEFAULT NULL,
  payment_status char(1) NOT NULL,
  payment_type_id varchar(255) NOT NULL,
  bank_statements_number int(11) DEFAULT NULL,
  is_cancelled tinyint(1) NOT NULL DEFAULT 0,
  created_by int(11) DEFAULT NULL,
  created_date datetime DEFAULT NULL,
  updated_by int(11) DEFAULT NULL,
  updated_date datetime DEFAULT NULL,
  PRIMARY KEY (payment_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `payers`
--
CREATE TABLE payers (
  payer_id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  full_name varchar(255) DEFAULT NULL,
  telephon_number varchar(255) DEFAULT NULL,
  old_telephon_number varchar(255) DEFAULT NULL,
  email varchar(50) DEFAULT NULL,
  bank_filter_id int(11) DEFAULT NULL,
  agreement_id int(11) DEFAULT NULL,
  billing_address varchar(255) DEFAULT NULL,
  PRIMARY KEY (payer_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `objects`
--
CREATE TABLE objects (
  object_id int(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Первичный ключ объекта (квартиры, паркоместа, подсобки)',
  house_address varchar(255) DEFAULT NULL,
  location varchar(255) DEFAULT NULL,
  payer_id int(11) NOT NULL,
  apartment_number int(11) DEFAULT NULL,
  apartment_code varchar(50) DEFAULT NULL,
  front_door_number int(11) DEFAULT NULL,
  front_door_code varchar(50) DEFAULT NULL,
  PRIMARY KEY (object_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
COMMENT = 'Таблица хранит список всех объектов управляемых организацией ОСББ и т.п. Вносятся все объекты, в том числе неоплачиваемые по ТП';

--
-- Create table `message_types`
--
CREATE TABLE message_types (
  message_type varchar(50) NOT NULL,
  PRIMARY KEY (message_type)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `messages`
--
CREATE TABLE messages (
  message_id int(11) NOT NULL AUTO_INCREMENT,
  payer_id int(11) DEFAULT NULL,
  message_type varchar(50) DEFAULT NULL,
  message_text varchar(500) DEFAULT NULL,
  send_date datetime DEFAULT NULL,
  updated datetime DEFAULT NULL,
  updated_by varchar(255) DEFAULT NULL,
  PRIMARY KEY (message_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `calendar`
--
CREATE TABLE calendar (
  calendar_id int(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'autoincrement value for the PK',
  c_date date NOT NULL,
  c_day int(20) UNSIGNED NOT NULL,
  c_is_work_day tinyint(1) NOT NULL,
  c_month int(20) UNSIGNED NOT NULL,
  c_year int(20) UNSIGNED NOT NULL COMMENT 'Year of date',
  c_quater int(20) UNSIGNED NOT NULL COMMENT 'quater of year',
  с_week int(11) UNSIGNED NOT NULL,
  PRIMARY KEY (calendar_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `business_items`
--
CREATE TABLE business_items (
  business_id varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (business_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `bills`
--
CREATE TABLE bills (
  bill_id int(11) NOT NULL AUTO_INCREMENT,
  payer_id int(11) DEFAULT NULL,
  period_id int(11) DEFAULT NULL,
  bill_amount decimal(15, 4) DEFAULT NULL,
  credit_account_id int(11) DEFAULT NULL,
  debet_account_id int(11) DEFAULT NULL,
  payment_date datetime DEFAULT NULL,
  payment_status char(1) DEFAULT NULL,
  PRIMARY KEY (bill_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `agreements`
--
CREATE TABLE agreements (
  agrement_id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  agreement_header varchar(255) DEFAULT NULL,
  payer_id int(11) DEFAULT NULL,
  can_be_published tinyint(1) DEFAULT NULL,
  PRIMARY KEY (agrement_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `accounts`
--
CREATE TABLE accounts (
  account_id int(11) NOT NULL AUTO_INCREMENT,
  payer_id int(11) NOT NULL,
  account_amount decimal(15, 4) NOT NULL,
  PRIMARY KEY (account_id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

-- 
-- Dumping data for table user_roles
--
-- Table utilbills.user_roles does not contain any data (it is empty)

-- 
-- Dumping data for table address_types
--
-- Table utilbills.address_types does not contain any data (it is empty)

-- 
-- Dumping data for table users
--
-- Table utilbills.users does not contain any data (it is empty)

-- 
-- Dumping data for table transactions
--
-- Table utilbills.transactions does not contain any data (it is empty)

-- 
-- Dumping data for table settings
--
-- Table utilbills.settings does not contain any data (it is empty)

-- 
-- Dumping data for table period_calendar
--
INSERT INTO period_calendar VALUES
(100, '2021-01-01', '2021-01-31'),
(101, '2021-02-01', '2021-02-28'),
(102, '2021-03-01', '2021-03-31'),
(103, '2021-04-01', '2021-04-30'),
(104, '2021-05-01', '2021-05-31'),
(105, '2021-06-01', '2021-06-30'),
(106, '2021-07-01', '2021-07-30'),
(107, '2021-08-01', '2021-08-31'),
(108, '2021-09-01', '2021-09-30'),
(109, '2021-10-01', '2021-10-31'),
(110, '2021-11-01', '2021-11-30'),
(111, '2021-12-01', '2021-12-31');

-- 
-- Dumping data for table payment_types
--
INSERT INTO payment_types VALUES
('Каждую неделю'),
('Каждый год'),
('Каждый квартал'),
('Каждый месяц');

-- 
-- Dumping data for table payment_transactions
--
-- Table utilbills.payment_transactions does not contain any data (it is empty)

-- 
-- Dumping data for table payment_statuses
--
-- Table utilbills.payment_statuses does not contain any data (it is empty)

-- 
-- Dumping data for table payments
--
-- Table utilbills.payments does not contain any data (it is empty)

-- 
-- Dumping data for table payers
--
-- Table utilbills.payers does not contain any data (it is empty)

-- 
-- Dumping data for table objects
--
-- Table utilbills.objects does not contain any data (it is empty)

-- 
-- Dumping data for table message_types
--
INSERT INTO message_types VALUES
('Почтовое с уведомлением'),
('Почтовое сообщение'),
('Сообщение в Telegram'),
('Сообщение в Viber'),
('Сообщение по email'),
('Требование об оплате'),
('Тяжелое требование при задолженности');

-- 
-- Dumping data for table messages
--
-- Table utilbills.messages does not contain any data (it is empty)

-- 
-- Dumping data for table calendar
--
-- Table utilbills.calendar does not contain any data (it is empty)

-- 
-- Dumping data for table business_items
--
INSERT INTO business_items VALUES
('Отопление'),
('Электричество');

-- 
-- Dumping data for table bills
--
-- Table utilbills.bills does not contain any data (it is empty)

-- 
-- Dumping data for table agreements
--
-- Table utilbills.agreements does not contain any data (it is empty)

-- 
-- Dumping data for table addresses
--
-- Table utilbills.addresses does not contain any data (it is empty)

-- 
-- Dumping data for table accounts
--
-- Table utilbills.accounts does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;