--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.688.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12.09.2021 10:43:07
-- Server version: 5.7.35
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO bills_local.address_types(address_type) VALUES
('Адрес объекта для оплаты');
INSERT INTO bills_local.address_types(address_type) VALUES
('Адрес плательщика для переписки');
INSERT INTO bills_local.address_types(address_type) VALUES
('Номер плательщика Whatsapp');
INSERT INTO bills_local.address_types(address_type) VALUES
('Номер плательщика в Telegram');
INSERT INTO bills_local.address_types(address_type) VALUES
('Номер плательщика в Viber');
INSERT INTO bills_local.address_types(address_type) VALUES
('Номер телефона плательщика');
INSERT INTO bills_local.address_types(address_type) VALUES
('Физический адрес регистрации плательщика');
INSERT INTO bills_local.address_types(address_type) VALUES
('Электронная почта плательщика');
INSERT INTO bills_local.address_types(address_type) VALUES
('Юридический адрес получателя (ОСББ)');