--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.688.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12.09.2021 10:43:07
-- Server version: 5.7.35
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO bills_local.business_items(business_id) VALUES
('Взносы на капитальный ремонт');
INSERT INTO bills_local.business_items(business_id) VALUES
('Вывоз мусора');
INSERT INTO bills_local.business_items(business_id) VALUES
('Оплата интернет-услуг');
INSERT INTO bills_local.business_items(business_id) VALUES
('Оплата телефонных услуг');
INSERT INTO bills_local.business_items(business_id) VALUES
('Отопление');
INSERT INTO bills_local.business_items(business_id) VALUES
('Поставка газа');
INSERT INTO bills_local.business_items(business_id) VALUES
('Поставка горячей воды');
INSERT INTO bills_local.business_items(business_id) VALUES
('Поставка холодной воды');
INSERT INTO bills_local.business_items(business_id) VALUES
('Поставка электричества');
INSERT INTO bills_local.business_items(business_id) VALUES
('Расходы на ведение ОСББ');
INSERT INTO bills_local.business_items(business_id) VALUES
('Уборка территории');