--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.688.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12.09.2021 10:43:47
-- Server version: 5.7.35
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO bills_local.message_types(message_type) VALUES
('Почтовое с уведомлением');
INSERT INTO bills_local.message_types(message_type) VALUES
('Почтовое сообщение');
INSERT INTO bills_local.message_types(message_type) VALUES
('Сообщение в Telegram');
INSERT INTO bills_local.message_types(message_type) VALUES
('Сообщение в Viber');
INSERT INTO bills_local.message_types(message_type) VALUES
('Сообщение по email');
INSERT INTO bills_local.message_types(message_type) VALUES
('Требование об оплате');
INSERT INTO bills_local.message_types(message_type) VALUES
('Тяжелое требование при задолженности');