--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.688.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12.09.2021 10:43:47
-- Server version: 5.7.35
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO bills_local.payment_types(payment_type_id) VALUES
('Каждую неделю');
INSERT INTO bills_local.payment_types(payment_type_id) VALUES
('Каждый год');
INSERT INTO bills_local.payment_types(payment_type_id) VALUES
('Каждый квартал');
INSERT INTO bills_local.payment_types(payment_type_id) VALUES
('Каждый месяц');