--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.688.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12.09.2021 10:43:47
-- Server version: 5.7.35
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO bills_local.period_calendar(period_id, start_date, end_date) VALUES
(100, '2021-01-01', '2021-01-31');
INSERT INTO bills_local.period_calendar(period_id, start_date, end_date) VALUES
(101, '2021-02-01', '2021-02-28');
INSERT INTO bills_local.period_calendar(period_id, start_date, end_date) VALUES
(102, '2021-03-01', '2021-03-31');
INSERT INTO bills_local.period_calendar(period_id, start_date, end_date) VALUES
(103, '2021-04-01', '2021-04-30');
INSERT INTO bills_local.period_calendar(period_id, start_date, end_date) VALUES
(104, '2021-05-01', '2021-05-31');
INSERT INTO bills_local.period_calendar(period_id, start_date, end_date) VALUES
(105, '2021-06-01', '2021-06-30');
INSERT INTO bills_local.period_calendar(period_id, start_date, end_date) VALUES
(106, '2021-07-01', '2021-07-30');
INSERT INTO bills_local.period_calendar(period_id, start_date, end_date) VALUES
(107, '2021-08-01', '2021-08-31');
INSERT INTO bills_local.period_calendar(period_id, start_date, end_date) VALUES
(108, '2021-09-01', '2021-09-30');
INSERT INTO bills_local.period_calendar(period_id, start_date, end_date) VALUES
(109, '2021-10-01', '2021-10-31');
INSERT INTO bills_local.period_calendar(period_id, start_date, end_date) VALUES
(110, '2021-11-01', '2021-11-30');
INSERT INTO bills_local.period_calendar(period_id, start_date, end_date) VALUES
(111, '2021-12-01', '2021-12-31');