--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.688.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12.09.2021 10:43:47
-- Server version: 5.7.35
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO bills_local.settings(setting_id, s_key, value, required, created_date, created_by, updated_date, updated_by) VALUES
(1, 'theme', 'dark', 1, NULL, NULL, '2021-09-01 18:14:20', 0);
INSERT INTO bills_local.settings(setting_id, s_key, value, required, created_date, created_by, updated_date, updated_by) VALUES
(2, 'round_money', '1.00', 1, '2021-08-31 19:41:56', NULL, '2021-09-01 18:14:20', 0);