--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.688.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 17.09.2021 21:50:57
-- Server version: 5.7.35
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO utilbills.user_roles(role_id, orderby) VALUES
('Администратор', 3),
('Бухгалтер', 5),
('Главный бухгалтер', 4),
('Директор', 1),
('Персонал', 6),
('Руководитель', 2);