--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.688.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12.09.2021 10:43:47
-- Server version: 5.7.35
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO bills_local.user_roles(role_id, orderby) VALUES
('Администратор', 3);
INSERT INTO bills_local.user_roles(role_id, orderby) VALUES
('Бухгалтер', 5);
INSERT INTO bills_local.user_roles(role_id, orderby) VALUES
('Главный бухгалтер', 4);
INSERT INTO bills_local.user_roles(role_id, orderby) VALUES
('Директор', 1);
INSERT INTO bills_local.user_roles(role_id, orderby) VALUES
('Персонал', 6);
INSERT INTO bills_local.user_roles(role_id, orderby) VALUES
('Руководитель', 2);